version: '3'
services:
  www:
    build: ./www
    ports:
     - "3000:3000"
  echo:
    build: ./echo
    ports:
     - "3001:3001"
  auth:
    image: quay.io/pusher/oauth2_proxy:v4.0.0
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:8000
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8000/oauth2/callback
      - OAUTH2_PROXY_UPSTREAMS=http://www:3000
    ports:
      - "8000:8000" # In prod, this is served on port 443