apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lightning
spec:
  environments:
    - name: development
      build:
        from: master
    - name: qa
      build:
        from: feature/timewriting
    - name: production
  components:
    - name: www
      src: ./www
      publicPort: http
      ports:
       - name: http
         port: 3000
    - name: echo
      src: ./echo
      ports:
       - name: http
         port: 3001
      environmentConfig:
        - environment: development
          replicas: 2
        - environment: production
          replicas: 2
  dnsAppAlias:
    environment: production
    component: www
