apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lightning
spec:
  environments:
    - name: development
      build:
        from: master
  components:
    - name: www
      src: ./www
      publicPort: http
      ports:
       - name: http
         port: 3000
      environmentConfig:
        - environment: development
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 16
          resources:
            requests:
              memory: "516Mi"
              cpu: "1000m"
            limits:
              memory: "516Mi"
    - name: echo
      src: ./echo
      ports:
       - name: http
         port: 3001
      environmentConfig:
        - environment: development
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 16
          resources:
            requests:
              memory: "516Mi"
              cpu: "1000m"
            limits:
              memory: "516Mi"
  dnsAppAlias:
    environment: production
    component: www
