apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lightning
spec:
  environments:
    - name: development
      build:
        from: master
    - name: production
      build:
        from: master
  components:
    - name: www
      image: nginx:latest
      # src: ./www
      publicPort: http
      ports:
       - name: http
         port: 80
    - name: echo
      src: ./echo
      ports:
       - name: http
         port: 3001
  dnsAppAlias:
    environment: development
    component: www
