apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lightning
spec:
  environments:
    - name: development
      build:
        from: master
    - name: production
      build:
        from: master
  components:
    - name: www
      src: ./radixconfigs
      publicPort: http
      ports:
       - name: http
         port: 80
  dnsAppAlias:
    environment: development
    component: www
